buildjob:
  stage: build
  tags:
    - dockercicd
  script:
    - docker build -t sahilksk/flaskapp:latest .
    - docker image push sahilksk/flaskapp:latest
    - aws ecs update-service -cluster sk-flaaskapp-cicd -service sk-flaskapp-cicd-service --force-new-deployment